#include<iostream>
#include <fstream>
#include <string>

#include "look_up_table_2d.h"

// Import data from a file
void import_data(std::string, std::vector<double> &);

int main(int argc, char *argv[]){

    std::vector<double> up_th_bp = {0, 11.176, 15.6464, 22.352, 40.2336, 44.704};
    std::vector<double> down_th_bp = {0, 2.2352, 17.8816, 22.352, 40.2336, 44.704};
    std::vector<double> gears = {1, 2, 3, 4};

    double _up_table[6][4] = {
        {4.4704,	13.4112,	22.352,	    447040},
        {4.4704,	13.4112,	22.352,	    447040},
        {6.7056,	13.4112,	22.352,	    447040},
        {10.28192,	18.32864,	26.822,	    447040},
        {17.8816,	31.2928,	44.704,	    447040},
        {17.8816,	31.2928,	44.704,	    447040},
    };

    double _down_table[6][4] = {
        {0,	    2.2352,	    8.9408,	    15.6464},
        {0,	    2.2352,	    8.9408,	    15.6464},
        {0,	    2.2352,	    11.176,	    17.8816},
        {0,	    2.2352,	    13.4112,	22.352},
        {0,	    13.4112,	22.352,	    35.7632},
        {0,	    13.4112,	22.352,	    35.7632},
    };

    std::vector<std::vector<double> > up_table(6), down_table(6); 

    for( int i = 0; i < up_th_bp.size(); i++){
        up_table[i].resize(4);
        down_table[i].resize(4);
        for( int j = 0; j < gears.size(); j++){
            up_table[i][j] = _up_table[i][j];
            down_table[i][j] = _down_table[i][j];
        }
    }

    LookUpTable2D interp_up_tbl(gears, up_th_bp);
    LookUpTable2D interp_down_tbl(gears, down_th_bp);

    interp_up_tbl.loadData(up_table);
    interp_down_tbl.loadData(down_table);

    // Import data generated by MATLAB
    std::vector<double> throttle_data, gear_data, up_th_data, down_th_data; 
    import_data("throtle.txt", throttle_data);
    import_data("gear.txt", gear_data);
    import_data("up_th.txt", up_th_data);
    import_data("down_th.txt", down_th_data);

    double interp_up_val, interp_down_val;

    // Compare 
    double delta = 0.001;
    bool success = true;
    for (int i = 0; i < throttle_data.size(); i++){
        interp_up_val = interp_up_tbl.getValue(gear_data[i], throttle_data[i]);
        if( abs(interp_up_val - up_th_data[i]) > delta ){
            std::cout << "*** ERROR IN CALCULATION OF UPPER THRESHOLD : " << interp_up_val << " != " << up_th_data[i] << std::endl;
            success = false; 
        }
        interp_down_val = interp_down_tbl.getValue(gear_data[i], throttle_data[i]);
        if( abs(interp_down_val - down_th_data[i]) > delta ){
            std::cout << "*** ERROR IN CALCULATION OF LOWER THRESHOLD : " << interp_down_val << " != " << down_th_data[i] << std::endl;
            success = false; 
        }
    }

    if (success) {
        std::cout << "Enhorabuena! Your results match those of MATLAB" << std::endl;
    }

    return 0;
}

void import_data(std::string filename, std::vector<double> &data){
    std::ifstream file;
    file.open(filename);
    std::string line;

    if (file.is_open()) {
        while (std::getline(file,line)) {
            double val = std::stod(line);
            data.push_back(val);
        }
        file.close();
    }
}