#include<iostream>
#include <fstream>
#include <string>

#include<systemc>

#include "look_up_table_2d.h"

#include "engine_torque_calculator.h"

// Import data from a file
void import_data(std::string, std::vector<double> &);

int sc_main(int argc, char *argv[]){

    // Import data generated by MATLAB
    std::vector<double> throttle_data, ne_data, te_data; 
    import_data("throttle_te_data.txt", throttle_data);
    import_data("te_data.txt", te_data);
    import_data("ne_data.txt", ne_data);

    double interp_te_val;

    EngineTorqueCalculator torque_calculator;

    // Compare 
    double delta = 0.001;
    bool success = true;
    int fail_count = 0;

    for (int i = 0; i < throttle_data.size(); i++){
        interp_te_val = torque_calculator.get_torque(ne_data[i], throttle_data[i]);
        if( abs(interp_te_val - te_data[i]) > delta ){
            std::cout << "*** ERROR IN CALCULATION: " << interp_te_val << " != " << te_data[i] << " i = " << i << std::endl;
            std::cout << "*** THROTTLE : " << throttle_data[i] << " NE: " << ne_data[i] << std::endl;
            success = false;
            fail_count++; 
        }
    }

    if (success) {
        std::cout << "Enhorabuena! Your results match those of MATLAB" << std::endl;
    }
    else{
        std::cout << "Domage ! " << fail_count << "/" << throttle_data.size() << " errors" << std::endl;
    }
    
    return 0;
}

void import_data(std::string filename, std::vector<double> &data){
    std::ifstream file;
    file.open(filename);
    std::string line;

    if (file.is_open()) {
        while (std::getline(file,line)) {
            double val = std::stod(line);
            data.push_back(val);
        }
        file.close();
    }
}